Update installplugins-mos
- add timeout (300s) to function file execution to avoid boot blocking for plugins

diff --git a/rootfs_files/etc/init.d/installplugins-mos b/rootfs_files/etc/init.d/installplugins-mos
--- a/rootfs_files/etc/init.d/installplugins-mos
+++ b/rootfs_files/etc/init.d/installplugins-mos
@@ -33,23 +33,15 @@ install_plugins() {
         DEBIAN_FRONTEND=noninteractive dpkg -i $PACKAGE_PATH >/dev/null 2>&1
         INSTALLATION_DONE=true
       fi
-      # Run functions file if found (in subshell to avoid using variables from function in mos_start)
+      # Run functions file if found with timeout to avoid boot blocking
       if [ -f "$VERSION_PATH/functions" ] ; then
-        (
-          source $VERSION_PATH/functions
-          if type mos_start &>/dev/null ; then
-            logger -t "MOS Plugins: $DISPLAY_NAME" "Executing start script"
-            mos_start 2>&1 | logger -t "MOS Plugins: $DISPLAY_NAME"
-            EXIT_STATUS=${PIPESTATUS[0]}
-            if [ "$EXIT_STATUS" != "0" ] ; then
-              logger -t "MOS Plugins: $DISPLAY_NAME" "ERROR: Running start script"
-              exit 1
-            else
-              logger -t "MOS Plugins: $DISPLAY_NAME" "Start script finished successful"
-              exit 0
-            fi
-          fi
-        )
+        logger -t "MOS Plugins: $DISPLAY_NAME" "Executing start script"
+        timeout -s KILL 300 bash -c '. "$1"; type mos_start >/dev/null 2>&1 && mos_start' bash "$VERSION_PATH/functions" 2>&1 | logger -t "MOS Plugins: $DISPLAY_NAME"
+        case "${PIPESTATUS[0]}" in
+          0)       logger -t "MOS Plugins: $DISPLAY_NAME" "Start script finished successful" ;;
+          124|137) logger -t "MOS Plugins: $DISPLAY_NAME" "ERROR: start script timed out" ;;
+          *)       logger -t "MOS Plugins: $DISPLAY_NAME" "ERROR: Running start script" ;;
+        esac
         INSTALLATION_DONE=true
       fi
     fi
